config/routes.rb
Mj::Application.routes.draw do
  devise_for :advertisers

root :to => "advertisements#index"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :user1s
  ActiveAdmin.routes(self)

  get "about/aboutus"

  match 'aboutus' => 'about#aboutus'


  resources :advertisements


  resources :feedbacks


  resources :events


  resources :relations


  resources :family_members


  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#sign_up", :as => "signup"
  get "search" => "users#search", :as => "search"
  get "rajasthan" => "sessions#about_rajasthan", :as => "rajasthan"
  get "demo_family" => "users#demo_family", :as => "demo_family"
  get "change_password" => "sessions#forgot", :as => "change_password"
  get "publish_event" => "events#new", :as => "publish_event"
  get "give_feedback" => "feedbacks#new", :as => "give_feedback"
  #root :to => "users#home"
 
 
  resources :users
  resources :sessions
  match ':controller(/:action(/:id))(.:format)'
end

app/models/family_member.rb
class FamilyMember < ActiveRecord::Base
  attr_accessible :family_member_user_id, :relationship, :user_id, :join_pending, :payment_status, :deactivate
  belongs_to :user
  belongs_to :relation
end

app/controllers/family_members_controller.rb
class FamilyMembersController < ApplicationController
  before_filter :already_logged_in
  skip_before_filter :already_logged_in, :only => [:family, :create_family, :admin_family, :add_family, :update_payment, :print_tree, :edit_relationship, :update_relation, :delete_member]

  def index
    @family_members = FamilyMember.all
  end

  def show
    @family_member = FamilyMember.find(params[:id])
  end

  def new
    @family_member = FamilyMember.new
  end

  def edit
    @family_member = FamilyMember.find(params[:id])
  end

  def create
    @family_member = FamilyMember.new(params[:family_member])
    @family_member.save
    redirect_to @family_member, notice: 'Family member was successfully created.'
  end

  def update
    @family_member = FamilyMember.find(params[:id])
    @family_member.update_attributes(params[:family_member])
    redirect_to @family_member, notice: 'Family member was successfully updated.'
  end

  def destroy
    @family_member = FamilyMember.find(params[:id])
    @family_member.destroy
    redirect_to family_members_url
  end

  def family
    @user = User.find(params[:id])
    @all_relations = Relation.all(:order => 'priority')
    @family_members = FamilyMember.find_all_by_family_member_user_id_and_join_pending(@user.id,true)
    @fm = FamilyMember.find_all_by_user_id_and_join_pending(@family_member_user_id, false)
    respond_to do |format|
      format.html
      format.xml { render :xml => @user }
      format.json { render :json => @user }
    format.pdf do
      render :pdf => "family"
    end
    end
  end

  def create_family
    @user = User.find(params[:id])
  end

  def add_family
    unless params[:relation] == "0"
      @user = User.find_by_mj_id(params[:search_mjid])
      unless @user.nil? or @user.blank?
        @fm = FamilyMember.find_by_user_id_and_family_member_user_id(current_user.id, @user.id)
        if @fm.nil? or @fm.blank?
          @f = FamilyMember.new
          @f.relation_id = params[:relation]
          @f.family_member_user_id = @user.id
          @f.user_id = @current_user.id
          @f.join_pending = false
          @f.save
          redirect_to "/family_members/family/#{current_user.id}", :notice => "#{@user.firstname} #{@user.lastname} added."
        else
          redirect_to "/family_members/family/#{current_user.id}", :notice => "#{@user.firstname} #{@user.lastname} already exists."
        end
      else
        redirect_to "/family_members/family/#{params[:id]}", :notice => "User does not exist."
      end
    else
      redirect_to "/family_members/family/#{params[:id]}", :notice => "Select a relation."
    end
    #@pending_members = FamilyMember.find_all_by_join_pending(true)
  end

  def join_pending
    @j = FamilyMember.find_by_id(params[:id])
    @j.update_attributes(:join_pending => false)
    @user = User.find(@j.user_id)
    @user.update_attributes(:family_count => @user.family_count + 1)
    @fm = FamilyMember.new
    @fm.relationship = "<" + @j.relationship + ">"
    @fm.family_member_user_id = @j.user_id
    @fm.user_id = @j.family_member_user_id
    @fm.save
    redirect_to "/family_members/family/#{@j.family_member_user_id}"
  end

  def join_decline
    @j = FamilyMember.find_by_id(params[:id])
    @j.destroy
    redirect_to "/family_members/family/#{@j.family_member_user_id}"
  end

  def admin_family
    @user = User.find(params[:id])
    @due_members = FamilyMember.find_all_by_payment_status_and_join_pending_and_user_id(false, false,params[:id])
    @paid_members = FamilyMember.find_all_by_payment_status_and_join_pending_and_user_id(true, false,params[:id])
  end

  def update_payment
    if params.include? "paid"
      params[:paid].each do |key,val|
        paid_user = FamilyMember.find_by_id(key)
        paid_user.update_attributes(:payment_status => true)
      end
      @user = User.find(params[:id])
      @due_members = FamilyMember.find_all_by_payment_status_and_join_pending_and_user_id(false, false,params[:id])
      @paid_members = FamilyMember.find_all_by_payment_status_and_join_pending_and_user_id(true, false,params[:id])
      @user.update_attributes(:payment => (@paid_members.count + 1) * 100)
      @user.update_attributes(:due => @due_members.count * 100)
      redirect_to "/family_members/admin_family/#{@user.id}"
    end
  end

  def deactivate
    @f = FamilyMember.find_by_id(params[:id])
    @f.update_attributes(:deactivate => true )
  end

  def print_tree
    @user = User.find(params[:id])
    @family_members = FamilyMember.find_all_by_family_member_user_id_and_join_pending(@user.id,true)
  end

  def delete_member
    @family_member = FamilyMember.find(params[:id])
    @family_member.destroy
    redirect_to "/family_members/family/#{current_user.id}", :notice => "Relationship deleted."
  end

end

app/helpers/family_members_helper.rb
module FamilyMembersHelper
end

app/views/family_members/_form.html.erb
<%= form_for(@family_member) do |f| %>
  <% if @family_member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@family_member.errors.count, "error") %> prohibited this family_member from being saved:</h2>

      <ul>
      <% @family_member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :family_member_user_id %><br />
    <%= f.text_field :family_member_user_id %>
  </div>
  <div class="field">
    <%= f.label :relationship %><br />
    <%= f.text_field :relationship %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/family_members/admin_family.erb
<center><h1>Family Members</h1>

  <%= @user.firstname %>'s family:<br/>
  <form action="/family_members/update_payment/<%= @user.id %>" method="post">
    <h3>Due members</h3>
    <table>
      <tr><th>Family member</th>
      </tr>

      <% @due_members.each do |d| %>
        <% family_member_user = User.find(d.family_member_user_id) %>
      <tr><td><%= family_member_user.firstname %><input type="checkbox" name="paid[<%= d.id %>]" value=""/>&nbsp;
          <% unless d.deactivate == true %> <a href="/family_members/deactivate/<%= d.id %>">Deactivate</a> <% end %></td>
        </tr>
        <% logger.info "check box is.... #{params}" %>

      <% end %>
    </table>
    <p class="button">
      <input type="submit" name="submit" value="Paid"/>&nbsp;
    </p>
    <br/>
    <h3>Paid members</h3>
    <table>
      <% @paid_members.each do |p| %>
        <% family_member_user = User.find(p.family_member_user_id) %>
        <tr><td><%= family_member_user.firstname %></td></tr>
      <% end %>
    </table>
    <br/>

  </form>

</center>
<br></br>
<a href="/sessions/login_page/<%= current_user.id %>">Back</a>

app/views/family_members/create_family.erb
<form action="/family_members/add_family/<%= @user.id %>" method="post">
<% @all_users = User.all(:order => 'firstname') %>
Name :
<select name="mj_id">
  	<option value="0">Select</option>
    <% @all_users.each do |user| %>
  		<option value="<%= user.mj_id %>"><%= user.firstname %> - <%= user.mj_id %></option>
  	<% end %>
</select>
<% @all_relations = Relation.all %>
Relation :
<select name="relation">
    <option value="0">Select</option>
    <% @all_relations.each do |relation| %>
  		<option value="<%= relation.id %>"><%= relation.id %> - <%= relation.relationship %></option>
  	<% end %>
</select>
 <p class="button">
<input type="submit" value="Add"/>
 </p></form>

app/views/family_members/edit.html.erb
<h1>Editing family_member</h1>

<%= render 'form' %>

<%= link_to 'Show', @family_member %> |
<%= link_to 'Back', family_members_path %>

app/views/family_members/family.erb
<!--<style type="text/css">
#topContact{display: none;}
</style>-->
<div id="content_links">
<a href="/users/edit_profile/<%= current_user.id %>">Profile</a>
<a href="/family_members/family/<%= current_user.id %>">Family Tree</a>
<a href="/give_feedback">Give feedback</a>
</div>
<!-- | <a href="" onclick="window.print()">Print</a> -->
<br/>
<div id="treeDiv">
<form action="/family_members/add_family/<%= current_user.id %>" method="post">
<% @all_users = User.all(:order => 'firstname') %>
<h2>Build your Family Tree</h2>
MJ Id <input type="text" size=3; name="search_mjid" />&nbsp;&nbsp;
Relation
<select name="relation" class="select_style">
    <option value="0">Select</option>
    <% @all_relations.each do |relation| %>
  		<option value="<%= relation.id %>"><%= relation.relationship %></option>
  	<% end %>
</select> &nbsp;&nbsp;
<input type="submit" value="Add member" class="button_style" />
<label class="notice"><%= notice %></label>
</form><br/>
<hr/>

<% @family_members.each do |r| %>
  would you like to join as <%= r.user.firstname  %> his/her <%= r.relationship %> ?
  <a href="/family_members/join_pending/<%= r.id %>">Accept</a><br/> | <a href="/family_members/join_decline/<%= r.id %>">Decline</a>
<% end %>
<h2><%= @user.firstname %> <%= @user.lastname %>'s Family</h2>
<center>
  <div class="MainProfile">
    <br/>
  <table >
    <tr>
      <td rowspan="7">
            <% if @user.photo_file_name.nil? %>
              <img src="/assets/empty_profile.jpeg" width="150" alt="" />
            <% else %>
               <%= image_tag @user.photo.url(:medium) %>
            <% end %>
      </td>
    </tr>
    <tr><td>Name:</td><td><%= @user.firstname %> <%= @user.lastname %></td></tr>
    <tr><td>Email:</td><td><%= @user.email %></td></tr>
    <tr><td>Mobile:</td><td><%= @user.mobileno %></td></tr>
    <tr><td>Gender:</td><td><%= @user.gender %></td></tr>
    <tr><td>Occupation:</td><td><%= @user.occupation %></td></tr>
    <tr><td>Station:</td><td><%= @user.station %></td></tr>
    <tr><td></td><td>Address:</td><td><%= @user.address %></td></tr>
  </table>     
  </div>
  <br/><br/>
  <table border="0px" class="familyTable">
    <tr><th>First Generation</th></tr>
    <tr>
      <% @user.relations.group("relationship").having("priority = ?", 1).order('id').each do |r| %>
      <td>
      <div class="relationGroup">
        <h1><%= r.relationship %></h1>
        <% r.family_members.where('user_id = ? and join_pending = ?',@user.id,false).each do |f| %>
           <% family_member_user = User.find(f.family_member_user_id) %>
           <% if family_member_user.photo_file_name.nil? %>
            <div class="relationGroupMember">
              <img src="/assets/empty_profile.jpeg" height="50" width="50" alt="" />
              <a href="/family_members/family/<%= family_member_user.id %>"><%= family_member_user.firstname %> <%= family_member_user.lastname %></a>
              <div class="memberMobile"><%= family_member_user.mobileno %></div>
              <div class="memberStation"><%= family_member_user.station %></div>
              <a href="/family_members/delete_member/<%= f.id %>"><img src="/assets/close.png"/></a>
            </div>
          <% else %>
            <% if f.deactivate == false  %>
              <div class="relationGroupMember">
                <%= image_tag family_member_user.photo.url(:small) %>
                <a href="/family_members/family/<%= family_member_user.id %>"><% end %> <%= family_member_user.firstname %> <%= family_member_user.lastname %></a>
                <div class="memberMobile"><%= family_member_user.mobileno %></div>
              <div class="memberStation"><%= family_member_user.station %></div>
              <a href="/family_members/delete_member/<%= f.id %>"><img src="/assets/close.png"/></a>
            </div>
          <% end %>
        <% end %>
        <div style="clear:both;"></div>
      </div>
      </td>
    <% end %>
    </tr>
  </table>
  <br></br>
  <table border="0px" class="familyTable">
    <tr><th>Second Generation</th></tr>
    <tr>
      <% @user.relations.group("relationship").having("priority = ?", 2).order('id').each do |r| %>
      <td>
      <div class="relationGroup">
        <h1><%= r.relationship %></h1>
        <% r.family_members.where('user_id = ? and join_pending = ?',@user.id,false).each do |f| %>
          <% family_member_user = User.find(f.family_member_user_id) %>
          <% if family_member_user.photo_file_name.nil? %>
            <!-- <td> -->
            <div class="relationGroupMember">
              <img src="/assets/empty_profile.jpeg" height="50" width="50" alt="" />
              <a href="/family_members/family/<%= family_member_user.id %>"><%=  family_member_user.firstname %> <%= family_member_user.lastname %></a>
              <div class="memberMobile"><%= family_member_user.mobileno %></div>
              <div class="memberStation"><%= family_member_user.station %></div>
              <% if current_user.id == @user.id %>
                <a href="/family_members/delete_member/<%= f.id %>"><img src="/assets/close.png"/></a>
              <% end %>
            </div>
            <!-- </td> -->
          <% else %>
            <% if f.deactivate == false  %>
              <!-- <td> -->
              <div class="relationGroupMember">
                <%= image_tag family_member_user.photo.url(:small) %>
                <a href="/family_members/family/<%= family_member_user.id %>"><% end %> <%=  family_member_user.firstname %> <%= family_member_user.lastname %></a>
                <div class="memberMobile"><%= family_member_user.mobileno %></div>
                <div class="memberStation"><%= family_member_user.station %></div>
                <% if current_user.id == @user.id %>
                  <a href="/family_members/delete_member/<%= f.id %>"><img src="/assets/close.png"/></a>
                <% end %>
            </div>
            <!-- </td> -->
          <% end %>
        <% end %>
        <div style="clear:both;"></div>
      </div>
      </td>
    <% end %>
       </tr>
  </table>
  <br></br>
  <table border="0px" class="familyTable">
    <tr><th>Third Generation</th></tr>
    <tr>
      <td>
        <div class="relationGroup">
        <h1>मैं</h1>
        <div class="relationGroupMember">
        <% if @user.photo_file_name.nil? %>
          <img src="/assets/empty_profile.jpeg" height="50" width="50" alt="" />
        <% else %>
          <%= image_tag @user.photo.url(:small) %>
        <% end %>
        <a href="#"><%= @user.firstname %> <%= @user.lastname %></a>
        <div class="memberMobile"><%= @user.mobileno %></div>
        <div class="memberStation"><%= @user.station %></div>
      </div>
      <div style="clear:both;"></div>
      </div>
      </td>
      <% @user.relations.group("relationship").having("priority = ?", 3).order('id').each do |r| %>
      <td>
      <div class="relationGroup">
        <h1><%= r.relationship %></h1>
        <% r.family_members.where('user_id = ? and join_pending = ?',@user.id,false).each do |f| %>
          <% family_member_user = User.find(f.family_member_user_id) %>
          <% if family_member_user.photo_file_name.nil? %>
            <!-- <td> -->
            <div class="relationGroupMember">
              <img src="/assets/empty_profile.jpeg" height="50" width="50" alt="" />
              <a href="/family_members/family/<%= family_member_user.id %>"><%= family_member_user.firstname %> <%= family_member_user.lastname %></a>
              <div class="memberMobile"><%= family_member_user.mobileno %></div>
              <div class="memberStation"><%= family_member_user.station %></div>
              <a href="/family_members/delete_member/<%= f.id %>"><img src="/assets/close.png"/></a>
            </div>
            <!-- </td> -->
          <% else %>
            <% if f.deactivate == false  %>
              <!-- <td> -->
              <div class="relationGroupMember">
                <%= image_tag family_member_user.photo.url(:small) %>
                <a href="/family_members/family/<%= family_member_user.id %>"><% end %> <%= family_member_user.firstname %> <%= family_member_user.lastname %></a>
                <div class="memberMobile"><%= family_member_user.mobileno %></div>
                <div class="memberStation"><%= family_member_user.station %></div>
                <a href="/family_members/delete_member/<%= f.id %>"><img src="/assets/close.png"/></a>
            </div>
            <!-- </td> -->
          <% end %>
        <% end %>
        <div style="clear:both;"></div>
      </div>
      </td>
    <% end %>
      </tr>
  </table>
  <br></br>
  <table border="0px" class="familyTable">
    <tr><th>Fourth Generation</th></tr>
    <tr>
      <% @user.relations.group("relationship").having("priority = ?", 4).order('id').each do |r| %>
      <td>
      <div class="relationGroup">
        <h1><%= r.relationship %></h1>
        <% r.family_members.where('user_id = ? and join_pending = ?',@user.id,false).each do |f| %>
          <% family_member_user = User.find(f.family_member_user_id) %>
          <% if family_member_user.photo_file_name.nil? %>
            <!-- <td> -->
            <div class="relationGroupMember">
              <img src="/assets/empty_profile.jpeg" height="50" width="50" alt="" />
              <a href="/family_members/family/<%= family_member_user.id %>"><%= family_member_user.firstname %> <%= family_member_user.lastname %></a>
              <div class="memberMobile"><%= family_member_user.mobileno %></div>
              <div class="memberStation"><%= family_member_user.station %></div>
              <a href="/family_members/delete_member/<%= f.id %>"><img src="/assets/close.png"/></a>
            </div>
            <!-- </td> -->
          <% else %>
            <% if f.deactivate == false  %>
              <!-- <td> -->
              <div class="relationGroupMember">
                <%= image_tag family_member_user.photo.url(:small) %>
                <a href="/family_members/family/<%= family_member_user.id %>"><% end %> <%= family_member_user.firstname %> <%= family_member_user.lastname %></a>
                <div class="memberMobile"><%= family_member_user.mobileno %></div>
                <div class="memberStation"><%= family_member_user.station %></div>
                <a href="/family_members/delete_member/<%= f.id %>"><img src="/assets/close.png"/></a>
            </div>
            <!-- </td> -->
          <% end %>
        <% end %>
        <div style="clear:both;"></div>
      </div>
      </td>
    <% end %>
    </tr>
  </table>
  <br></br>
</center>

</div>

app/views/family_members/index.html.erb
<h1>Listing family_members</h1>

<table>
  <tr>
    <th>User</th>
    <th>Family member user</th>
    <th>Relationship</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @family_members.each do |family_member| %>
  <tr>
    <td><%= family_member.user_id %></td>
    <td><%= family_member.family_member_user_id %></td>
    <td><%= family_member.relationship %></td>
    <td><%= link_to 'Show', family_member %></td>
    <td><%= link_to 'Edit', edit_family_member_path(family_member) %></td>
    <td><%= link_to 'Destroy', family_member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Family member', new_family_member_path %>

app/views/family_members/new.html.erb
<h1>New family_member</h1>

<%= render 'form' %>

<%= link_to 'Back', family_members_path %>

app/views/family_members/print_tree.erb
<body onload="window.print()">
<% @family_members.each do |r| %>
  would you like to join as <%= r.user.firstname  %> his/her <%= r.relationship %> ?
  <a href="/family_members/join_pending/<%= r.id %>">Accept</a><br/> | <a href="/family_members/join_decline/<%= r.id %>">Decline</a>
<% end %>
<a href="/sessions/login_page/<%= current_user.id%>">Home Page</a> |
<a href="/family_members/family/<%= current_user.id%>">Show My Family</a>
<center><h1>Family Members</h1>

  <%= @user.firstname %>'s family:<br/>

  <table>
    <tr>
      <th></th>
      <th>Family member</th>
      <th>Relationship</th>
    </tr>
    <% @user.relations.group("priority").each do |r| %>
      <tr><% r.family_members.where('user_id = ? and join_pending = ?',@user.id,false).each do |f| %>
          <% family_member_user = User.find(f.family_member_user_id) %>
          <% if family_member_user.photo_file_name.nil? %>
            <td>
              <img src="/assets/empty_profile.jpeg" height="30" width="30" alt="" />
            </td>
            <td><a href="/family_members/family/<%= family_member_user.id %>"><%=  family_member_user.firstname %></a>
            </td>
            <td><%= f.relation.relationship %></td>
          <% else %>
            <% if f.deactivate == false  %>
              <td>
                <%= image_tag family_member_user.photo.url(:small) %>
              </td>
              <td>
                <a href="/family_members/family/<%= family_member_user.id %>"><% end %> <%=  family_member_user.firstname %></a>
            </td>
            <td><%=  f.relation.relationship %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </table>
  <br></br>

</center>
</body>

app/views/family_members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @family_member.user_id %>
</p>

<p>
  <b>Family member user:</b>
  <%= @family_member.family_member_user_id %>
</p>

<p>
  <b>Relationship:</b>
  <%= @family_member.relationship %>
</p>


<%= link_to 'Edit', edit_family_member_path(@family_member) %> |
<%= link_to 'Back', family_members_path %>