config/routes.rb
Mj::Application.routes.draw do
  devise_for :advertisers

root :to => "advertisements#index"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :user1s
  ActiveAdmin.routes(self)

  get "about/aboutus"

  match 'aboutus' => 'about#aboutus'


  resources :advertisements


  resources :feedbacks


  resources :events


  resources :relations


  resources :family_members


  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#sign_up", :as => "signup"
  get "search" => "users#search", :as => "search"
  get "rajasthan" => "sessions#about_rajasthan", :as => "rajasthan"
  get "demo_family" => "users#demo_family", :as => "demo_family"
  get "change_password" => "sessions#forgot", :as => "change_password"
  get "publish_event" => "events#new", :as => "publish_event"
  get "give_feedback" => "feedbacks#new", :as => "give_feedback"
  #root :to => "users#home"
 
 
  resources :users
  resources :sessions
  match ':controller(/:action(/:id))(.:format)'
end

app/models/relation.rb
class Relation < ActiveRecord::Base
  attr_accessible :relationship, :priority
  has_many :family_members
  has_many :users, :through => :family_members
end

app/controllers/relations_controller.rb
class RelationsController < ApplicationController
  # before_filter :already_logged_in
  # GET /relations
  # GET /relations.json
  def index
    @relations = Relation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @relations }
    end
  end

  # GET /relations/1
  # GET /relations/1.json
  def show
    @relation = Relation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @relation }
    end
  end

  # GET /relations/new
  # GET /relations/new.json
  def new
    @relation = Relation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @relation }
    end
  end

  # GET /relations/1/edit
  def edit
    @relation = Relation.find(params[:id])
  end

  # POST /relations
  # POST /relations.json
  def create
    @relation = Relation.new(params[:relation])

    respond_to do |format|
      if @relation.save
        format.html { redirect_to relations_url, notice: 'Relation was successfully created.' }
        format.json { render json: @relation, status: :created, location: @relation }
      else
        format.html { render action: "new" }
        format.json { render json: @relation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /relations/1
  # PUT /relations/1.json
  def update
    @relation = Relation.find(params[:id])

    respond_to do |format|
      if @relation.update_attributes(params[:relation])
        format.html { redirect_to relations_url, notice: 'Relation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @relation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /relations/1
  # DELETE /relations/1.json
  def destroy
    @relation = Relation.find(params[:id])
    @relation.destroy

    respond_to do |format|
      format.html { redirect_to relations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/relations_helper.rb
module RelationsHelper
end

app/views/relations/_form.html.erb
<%= form_for(@relation) do |f| %>
  <% if @relation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@relation.errors.count, "error") %> prohibited this relation from being saved:</h2>

      <ul>
      <% @relation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :relationship %><br />
    <%= f.text_field :relationship %>
  </div>
  <div class="field">
    <%= f.label :priority %><br />
    <%= f.text_field :priority %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/relations/edit.html.erb
<h1>Editing relation</h1>

<%= render 'form' %>

<%= link_to 'Show', @relation %> |
<%= link_to 'Back', relations_path %>

app/views/relations/index.html.erb
<div id="content_links">
  <a href="/users?begin=15">Users</a>
  <a href="/family_members">Family members</a>
  <a href="/relations">Relations</a>
  <a href="/feedbacks">View Feedbacks</a>
  <a href="/publish_event">Publish Event</a>
</div>
<h2>Relations</h2>

<table>
  <tr>
    <th>Id</th>
    <th>Relationship</th>
    <th>Priority</th>
    <th></th>
  </tr>

<% @relations.each do |relation| %>
  <tr>
    <td><%= relation.id %></td>
    <td><%= relation.relationship %></td>
    <td><%= relation.priority %></td>
    <td><%= link_to 'Edit', edit_relation_path(relation) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Relation', new_relation_path %>

app/views/relations/new.html.erb
<h1>New relation</h1>

<%= render 'form' %>

<%= link_to 'Back', relations_path %>

app/views/relations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Relationship:</b>
  <%= @relation.relationship %>
</p>


<%= link_to 'Edit', edit_relation_path(@relation) %> |
<%= link_to 'Back', relations_path %>