config/routes.rb
Mj::Application.routes.draw do
  devise_for :advertisers

root :to => "advertisements#index"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :user1s
  ActiveAdmin.routes(self)

  get "about/aboutus"

  match 'aboutus' => 'about#aboutus'


  resources :advertisements


  resources :feedbacks


  resources :events


  resources :relations


  resources :family_members


  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#sign_up", :as => "signup"
  get "search" => "users#search", :as => "search"
  get "rajasthan" => "sessions#about_rajasthan", :as => "rajasthan"
  get "demo_family" => "users#demo_family", :as => "demo_family"
  get "change_password" => "sessions#forgot", :as => "change_password"
  get "publish_event" => "events#new", :as => "publish_event"
  get "give_feedback" => "feedbacks#new", :as => "give_feedback"
  #root :to => "users#home"
 
 
  resources :users
  resources :sessions
  match ':controller(/:action(/:id))(.:format)'
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  attr_accessible :details, :user_id
  belongs_to :user
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController

  def index
    @feedbacks = Feedback.all
  end

  def show
    @feedback = Feedback.find(params[:id])
  end

  def new
    @feedback = Feedback.new
  end

  def edit
    @feedback = Feedback.find(params[:id])
  end

  def create
    @feedback = Feedback.new(params[:feedback])
    @feedback.user_id = current_user.id
    @feedback.save
    redirect_to feedbacks_url, notice: 'Feedback was successfully created.'
  end

  def update
    @feedback = Feedback.find(params[:id])
    @feedback.update_attributes(params[:feedback])
    redirect_to feedbacks_url, notice: 'Feedback was successfully updated.'
  end

  def destroy
    @feedback = Feedback.find(params[:id])
    @feedback.destroy
    redirect_to feedbacks_url
  end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/_form.html.erb
<%= form_for(@feedback) do |f| %>
  <% if @feedback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feedback.errors.count, "error") %> prohibited this feedback from being saved:</h2>

      <ul>
      <% @feedback.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :details %><br />
    <%= f.text_area :details %>
  </div>
<br/>
  <div class="actions">
    <%= f.submit :class => "button_style" %>
  </div>
<% end %>

app/views/feedbacks/edit.html.erb
<h1>Editing feedback</h1>

<%= render 'form' %>

<%= link_to 'Show', @feedback %> |
<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/index.html.erb
<% if current_user.user_id == 0 %>
<div id="content_links">
  <a href="/users?begin=15">Users</a>
  <a href="/family_members">Family members</a>
  <a href="/relations">Relations</a>
  <a href="/feedbacks">View Feedbacks</a>
  <a href="/publish_event">Publish Event</a>
</div>
<% else %>
<div id="content_links">
  <a href="/users/edit_profile/<%= current_user.id %>">Profile</a>
  <a href="/family_members/family/<%= current_user.id %>">Family Tree</a>
  <a href="/feedbacks">Feedback</a>
  <a href="/feedbacks/new">Give feedback</a>
</div>
<% end %>
<h2>Feedback</h2>

<table>
  <tr>
    <th>MJ ID</th>
    <th>Details</th>
  </tr>

<% @feedbacks.each do |feedback| %>
  <tr>
    <td><%= feedback.user.mj_id %></td>
    <td><%= feedback.details %></td>
    <!-- <td><%#= link_to 'Edit', edit_feedback_path(feedback) %></td> -->
    <!-- <td><%#= link_to 'Destroy', feedback, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
  </tr>
<% end %>
</table>

app/views/feedbacks/new.html.erb
<div id="content_links">
<a href="/users/edit_profile/<%= current_user.id %>">Profile</a>
<a href="/family_members/family/<%= current_user.id %>">Family Tree</a>
<a href="/give_feedback">Give feedback</a>
</div>
<h2>Give your feedback</h2>
<%= render 'form' %>

app/views/feedbacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Details:</b>
  <%= @feedback.details %>
</p>

<p>
  <b>User:</b>
  <%= @feedback.user_id %>
</p>


<%= link_to 'Edit', edit_feedback_path(@feedback) %> |
<%= link_to 'Back', feedbacks_path %>